create database students;
show databases;
use students;
create table guvi(userid varchar(8),name char(50),toprank int(3));
describe guvi;
insert into guvi (userid,name,toprank) values("15bee043","yuvasree",4);
insert into guvi (userid,name,toprank) values("15bee037","muunthan",3);
insert into guvi (userid,name,toprank) values("15bee084","rahasudha",2);
select * from guvi;
CREATE INDEX idx_toprank ON guvi (toprank);
select*from guvi;
DROP INDEX guvi.idx_toprank;
